apiVersion: v1
kind: Service
metadata:
  name: cilium-gateway-internal-clusterip
  namespace: kube-system
spec:
  type: ClusterIP
  selector:
    k8s-app: cilium-envoy
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
