apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: authentik-secrets
  data:
    - secretKey: secret-key
      remoteRef:
        key: authentik-secret-key
    - secretKey: db-password
      remoteRef:
        key: authentik-db-password
    - secretKey: vaultwarden-oidc-client-id
      remoteRef:
        key: vaultwarden-sso-client-id
    - secretKey: vaultwarden-oidc-client-secret
      remoteRef:
        key: vaultwarden-sso-client-secret
    - secretKey: grafana-oidc-client-id
      remoteRef:
        key: grafana-oidc-client-id
    - secretKey: grafana-oidc-client-secret
      remoteRef:
        key: grafana-oidc-client-secret
    - secretKey: argocd-oidc-client-id
      remoteRef:
        key: argocd-oidc-client-id
    - secretKey: argocd-oidc-client-secret
      remoteRef:
        key: argocd-oidc-client-secret
