apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: authentik
    repo: https://charts.goauthentik.io
    version: "2026.2.1"
    releaseName: authentik
    namespace: identity
    valuesInline:
      fullnameOverride: authentik
      global:
        env:
          - name: AUTHENTIK_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: authentik-secrets
                key: secret-key
          - name: AUTHENTIK_POSTGRESQL__PASSWORD
            valueFrom:
              secretKeyRef:
                name: authentik-secrets
                key: db-password
          - name: VAULTWARDEN_OIDC_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: authentik-secrets
                key: vaultwarden-oidc-client-id
          - name: VAULTWARDEN_OIDC_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: authentik-secrets
                key: vaultwarden-oidc-client-secret
          - name: GRAFANA_OIDC_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: authentik-secrets
                key: grafana-oidc-client-id
          - name: GRAFANA_OIDC_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: authentik-secrets
                key: grafana-oidc-client-secret
          - name: ARGOCD_OIDC_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: authentik-secrets
                key: argocd-oidc-client-id
          - name: ARGOCD_OIDC_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: authentik-secrets
                key: argocd-oidc-client-secret
      authentik:
        postgresql:
          host: postgres-rw.postgres.svc
          name: authentik
          user: authentik
      server:
        replicas: 1
        priorityClassName: platform
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 768Mi
      worker:
        replicas: 1
        priorityClassName: platform
        resources:
          requests:
            cpu: 50m
            memory: 384Mi
          limits:
            memory: 512Mi
      postgresql:
        enabled: false
      blueprints:
        configMaps:
          - blueprint-vaultwarden
          - blueprint-grafana
          - blueprint-argocd

resources:
  - externalsecret.yaml
  - httproute.yaml
  - blueprint-vaultwarden.yaml
  - blueprint-grafana.yaml
  - blueprint-argocd.yaml
