apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: vaultwarden-secrets
  data:
    - secretKey: admin-token
      remoteRef:
        key: vaultwarden-admin-token
    - secretKey: sso-client-id
      remoteRef:
        key: vaultwarden-sso-client-id
    - secretKey: sso-client-secret
      remoteRef:
        key: vaultwarden-sso-client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-db-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: vaultwarden-db-credentials
    template:
      data:
        database-url: "postgresql://vaultwarden:{{ .password }}@postgres-rw.postgres.svc:5432/vaultwarden"
  data:
    - secretKey: password
      remoteRef:
        key: vaultwarden-db-password
