apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: grafana-oidc
  data:
    - secretKey: client_id
      remoteRef:
        key: grafana-oidc-client-id
    - secretKey: client_secret
      remoteRef:
        key: grafana-oidc-client-secret
