apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: immich-db-credentials
    template:
      data:
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: immich-db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: immich-config
    template:
      data:
        immich-config.yaml: |
          oauth:
            enabled: true
            issuerUrl: https://auth.home.demivan.me/application/o/immich/
            clientId: "{{ .clientId }}"
            clientSecret: "{{ .clientSecret }}"
            scope: openid email profile
            buttonText: Login with Authentik
            autoLaunch: false
            autoRegister: true
            mobileOverrideEnabled: false
            signingAlgorithm: RS256
            tokenEndpointAuthMethod: client_secret_post
          passwordLogin:
            enabled: false
  data:
    - secretKey: clientId
      remoteRef:
        key: immich-oidc-client-id
    - secretKey: clientSecret
      remoteRef:
        key: immich-oidc-client-secret
