apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: minecraft
  namespace: minecraft
spec:
  networkRouterRef:
    name: homelab
    namespace: netbird
  serviceRef:
    name: mc-router
  groups:
    - name: All
