apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway-class.yaml
  - certificate.yaml
  - gateway.yaml
  - public-gateway-class.yaml
  - public-certificate.yaml
  - public-gateway.yaml
