apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: cilium-gateway-internal
  namespace: cilium-gateway
spec:
  networkRouterRef:
    name: homelab
    namespace: netbird
  serviceRef:
    name: cilium-gateway-internal
  groups:
    - name: All
