apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: "9.4.17"
    releaseName: argocd
    namespace: argocd
    valuesInline:
      global:
        domain: argocd.home.demivan.me
      configs:
        cm:
          kustomize.buildOptions: --enable-helm
          admin.enabled: "false"
          oidc.config: |
            name: Authentik
            issuer: https://auth.home.demivan.me/application/o/argocd/
            clientID: $argocd-oidc-secret:oidc.default.clientID
            clientSecret: $argocd-oidc-secret:oidc.default.clientSecret
            scopes:
              - openid
              - profile
              - email
        rbac:
          policy.csv: |
            g, admin, role:admin
        params:
          server.insecure: true
          controller.diff.server.side: "true"
      server:
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 256Mi
        priorityClassName: platform
      controller:
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 512Mi
        priorityClassName: platform
      repoServer:
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 256Mi
        priorityClassName: platform
      redis:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 128Mi

resources:
  - httproute.yaml
  - externalsecret.yaml
