apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hcloud
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: hcloud
  data:
    - secretKey: token
      remoteRef:
        key: hcloud-token
    - secretKey: network
      remoteRef:
        key: hcloud-network
