apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stalwart-recovery-admin
  namespace: stalwart
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: stalwart-recovery-admin
    template:
      data:
        username: recovery
        password: "{{ .password }}"
        credential: "recovery:{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: stalwart-recovery-admin-password
