# Requires the SMB subdir `music/library` to already exist on the Storage Box.
# Created once (manually) — see docs/superpowers/plans (Task 2). If missing,
# this PV mounts with: mount error(2): No such file or directory.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-library
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3.0
    - file_mode=0644
    - dir_mode=0755
    - uid=0
    - gid=0
    - noperm
    - noserverino
    - cache=strict
    - actimeo=30
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: lidarr-library
    volumeAttributes:
      source: "//u569043.your-storagebox.de/backup"
      subDir: "music/library"
    nodeStageSecretRef:
      name: smb-credentials
      namespace: csi-driver-smb
