apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: lidarr
  annotations:
    k8up.io/backup: "false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
