apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: library
  namespace: lidarr
  annotations:
    k8up.io/backup: "false"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: lidarr-library
  resources:
    requests:
      storage: 100Gi
