apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: authentik-db
spec:
  name: authentik
  owner: authentik
  cluster:
    name: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: vaultwarden-db
spec:
  name: vaultwarden
  owner: vaultwarden
  cluster:
    name: postgres
