apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: b2-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: b2-credentials
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: b2-key-id
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: b2-app-key
