apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-db-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: authentik-db-credentials
    template:
      type: kubernetes.io/basic-auth
      data:
        username: authentik
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: authentik-db-password
