apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: b2-backup-store
spec:
  configuration:
    destinationPath: "s3://demivan-homelab-backup/cnpg/"
    endpointURL: "https://s3.eu-central-003.backblazeb2.com"
    s3Credentials:
      accessKeyId:
        name: b2-credentials
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: b2-credentials
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
    data:
      compression: gzip
  retentionPolicy: "30d"
  instanceSidecarConfiguration:
    env:
      - name: AWS_REQUEST_CHECKSUM_CALCULATION
        value: when_required
      - name: AWS_RESPONSE_CHECKSUM_VALIDATION
        value: when_required
