apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smb-credentials
  namespace: csi-driver-smb
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: smb-credentials
  data:
    - secretKey: username
      remoteRef:
        key: storagebox-username
    - secretKey: password
      remoteRef:
        key: storagebox-password
