server_tokens off;

server {
    listen 8443 ssl default_server;
    http2 on;
    server_name mta-sts.demivan.me mta-sts.lab.demivan.me;

    ssl_certificate     /tls/tls.crt;
    ssl_certificate_key /tls/tls.key;
    ssl_protocols       TLSv1.2 TLSv1.3;

    location = /.well-known/mta-sts.txt {
        default_type text/plain;
        alias /policy/mta-sts.txt;
    }

    location / {
        return 404;
    }
}
