apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbird-api-key
  namespace: netbird
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: netbird-api-key
  data:
    - secretKey: NB_API_KEY
      remoteRef:
        key: netbird-api-key
