apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kubernetes-operator
    repo: https://netbirdio.github.io/helms
    version: "0.3.1"
    releaseName: netbird
    namespace: netbird
    includeCRDs: true
    valuesInline:
      webhook:
        enableCertManager: true
      netbirdAPI:
        keyFromSecret:
          name: netbird-api-key
          key: NB_API_KEY

resources:
  - externalsecret.yaml
