apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: backup
  namespace: adventurelog
spec:
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  backend:
    repoPasswordSecretRef:
      name: backup-credentials
      key: password
    b2:
      bucket: demivan-homelab-backup
      path: k8up/adventurelog
      accountIDSecretRef:
        name: backup-credentials
        key: b2-key-id
      accountKeySecretRef:
        name: backup-credentials
        key: b2-app-key
  backup:
    schedule: "45 3 * * *"
  check:
    schedule: "30 4 * * 1"
  prune:
    schedule: "30 4 * * 0"
    retention:
      keepLast: 5
      keepDaily: 7
      keepWeekly: 4
      keepMonthly: 6
