apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: backup-credentials
spec:
  namespaceSelectors:
    - matchLabels:
        backup: enabled
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: infisical
    target:
      name: backup-credentials
    data:
      - secretKey: password
        remoteRef:
          key: restic-repo-password
      - secretKey: b2-key-id
        remoteRef:
          key: b2-key-id
      - secretKey: b2-app-key
        remoteRef:
          key: b2-app-key
